# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_absorber_vmr_imp_base', [dirname(__file__)])
        except ImportError:
            import _absorber_vmr_imp_base
            return _absorber_vmr_imp_base
        if fp is not None:
            try:
                _mod = imp.load_module('_absorber_vmr_imp_base', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _absorber_vmr_imp_base = swig_import_helper()
    del swig_import_helper
else:
    import _absorber_vmr_imp_base
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except Exception:
    weakref_proxy = lambda x: x



_absorber_vmr_imp_base.SHARED_PTR_DISOWN_swigconstant(_absorber_vmr_imp_base)
SHARED_PTR_DISOWN = _absorber_vmr_imp_base.SHARED_PTR_DISOWN

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import full_physics_swig.state_vector
import full_physics_swig.generic_object
import full_physics_swig.sub_state_vector_array
import full_physics_swig.absorber_vmr
class SubStateVectorArrayAbsorberVmr(full_physics_swig.absorber_vmr.AbsorberVmr, full_physics_swig.state_vector.SubStateVectorObserver):
    __swig_setmethods__ = {}
    for _s in [full_physics_swig.absorber_vmr.AbsorberVmr, full_physics_swig.state_vector.SubStateVectorObserver]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SubStateVectorArrayAbsorberVmr, name, value)
    __swig_getmethods__ = {}
    for _s in [full_physics_swig.absorber_vmr.AbsorberVmr, full_physics_swig.state_vector.SubStateVectorObserver]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SubStateVectorArrayAbsorberVmr, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def init(self, *args):
        return _absorber_vmr_imp_base.SubStateVectorArrayAbsorberVmr_init(self, *args)
    __swig_destroy__ = _absorber_vmr_imp_base.delete_SubStateVectorArrayAbsorberVmr
    __del__ = lambda self: None

    def mark_used_sub(self, Used):
        return _absorber_vmr_imp_base.SubStateVectorArrayAbsorberVmr_mark_used_sub(self, Used)

    def state_vector_name_i(self, i):
        return _absorber_vmr_imp_base.SubStateVectorArrayAbsorberVmr_state_vector_name_i(self, i)

    def state_vector_name_sub(self, Sv_name):
        return _absorber_vmr_imp_base.SubStateVectorArrayAbsorberVmr_state_vector_name_sub(self, Sv_name)

    def update_sub_state(self, Sv_sub, Cov):
        return _absorber_vmr_imp_base.SubStateVectorArrayAbsorberVmr_update_sub_state(self, Sv_sub, Cov)

    def update_sub_state_hook(self):
        return _absorber_vmr_imp_base.SubStateVectorArrayAbsorberVmr_update_sub_state_hook(self)

    def _v_coefficient(self):
        return _absorber_vmr_imp_base.SubStateVectorArrayAbsorberVmr__v_coefficient(self)

    @property
    def coefficient(self):
        return self._v_coefficient()


    def _v_used_flag_value(self):
        return _absorber_vmr_imp_base.SubStateVectorArrayAbsorberVmr__v_used_flag_value(self)

    @property
    def used_flag_value(self):
        return self._v_used_flag_value()


    def _v_statevector_covariance(self):
        return _absorber_vmr_imp_base.SubStateVectorArrayAbsorberVmr__v_statevector_covariance(self)

    @property
    def statevector_covariance(self):
        return self._v_statevector_covariance()


    def _v_pressure(self):
        return _absorber_vmr_imp_base.SubStateVectorArrayAbsorberVmr__v_pressure(self)

    @property
    def pressure(self):
        return self._v_pressure()

SubStateVectorArrayAbsorberVmr_swigregister = _absorber_vmr_imp_base.SubStateVectorArrayAbsorberVmr_swigregister
SubStateVectorArrayAbsorberVmr_swigregister(SubStateVectorArrayAbsorberVmr)

class AbsorberVmrImpBase(SubStateVectorArrayAbsorberVmr):
    __swig_setmethods__ = {}
    for _s in [SubStateVectorArrayAbsorberVmr]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AbsorberVmrImpBase, name, value)
    __swig_getmethods__ = {}
    for _s in [SubStateVectorArrayAbsorberVmr]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, AbsorberVmrImpBase, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _absorber_vmr_imp_base.delete_AbsorberVmrImpBase
    __del__ = lambda self: None

    def clone(self, *args):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_clone(self, *args)

    def _v_gas_name(self):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase__v_gas_name(self)

    @property
    def gas_name(self):
        return self._v_gas_name()


    def volume_mixing_ratio(self, P):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_volume_mixing_ratio(self, P)

    def _v_state_used(self):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase__v_state_used(self)

    @property
    def state_used(self):
        return self._v_state_used()


    def add_observer(self, Obs):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_add_observer(self, Obs)

    def remove_observer(self, Obs):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_remove_observer(self, Obs)

    def update_sub_state_hook(self):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_update_sub_state_hook(self)

    def print_desc(self, Os):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_print_desc(self, Os)

    def _v_desc(self):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase__v_desc(self)

    @property
    def desc(self):
        return self._v_desc()


    def mark_used(self, Sv, Used):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_mark_used(self, Sv, Used)

    def state_vector_name(self, Sv, Sv_name):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_state_vector_name(self, Sv, Sv_name)

    def notify_update(self, Observed_object):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_notify_update(self, Observed_object)

    def notify_add(self, Observed_object):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_notify_add(self, Observed_object)

    def notify_remove(self, Observed_object):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_notify_remove(self, Observed_object)

    def update_sub_state(self, Sv_sub, Cov_sub):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_update_sub_state(self, Sv_sub, Cov_sub)

    def state_vector_name_i(self, i):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_state_vector_name_i(self, i)

    def state_vector_name_sub(self, Sv_name):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_state_vector_name_sub(self, Sv_name)
    __swig_setmethods__["cache_stale"] = _absorber_vmr_imp_base.AbsorberVmrImpBase_cache_stale_set
    __swig_getmethods__["cache_stale"] = _absorber_vmr_imp_base.AbsorberVmrImpBase_cache_stale_get
    if _newclass:
        cache_stale = _swig_property(_absorber_vmr_imp_base.AbsorberVmrImpBase_cache_stale_get, _absorber_vmr_imp_base.AbsorberVmrImpBase_cache_stale_set)
    __swig_setmethods__["vmr"] = _absorber_vmr_imp_base.AbsorberVmrImpBase_vmr_set
    __swig_getmethods__["vmr"] = _absorber_vmr_imp_base.AbsorberVmrImpBase_vmr_get
    if _newclass:
        vmr = _swig_property(_absorber_vmr_imp_base.AbsorberVmrImpBase_vmr_get, _absorber_vmr_imp_base.AbsorberVmrImpBase_vmr_set)

    def calc_vmr(self):
        return _absorber_vmr_imp_base.AbsorberVmrImpBase_calc_vmr(self)

    def __init__(self, Gas_name, Coeff, Used_flag, Press, Mark_according_to_press=True, Pdep_start=0):
        if self.__class__ == AbsorberVmrImpBase:
            _self = None
        else:
            _self = self
        this = _absorber_vmr_imp_base.new_AbsorberVmrImpBase(_self, Gas_name, Coeff, Used_flag, Press, Mark_according_to_press, Pdep_start)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    def __disown__(self):
        self.this.disown()
        _absorber_vmr_imp_base.disown_AbsorberVmrImpBase(self)
        return weakref_proxy(self)
AbsorberVmrImpBase_swigregister = _absorber_vmr_imp_base.AbsorberVmrImpBase_swigregister
AbsorberVmrImpBase_swigregister(AbsorberVmrImpBase)

# This file is compatible with both classic and new-style classes.


