# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_gas_vmr_apriori', [dirname(__file__)])
        except ImportError:
            import _gas_vmr_apriori
            return _gas_vmr_apriori
        if fp is not None:
            try:
                _mod = imp.load_module('_gas_vmr_apriori', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _gas_vmr_apriori = swig_import_helper()
    del swig_import_helper
else:
    import _gas_vmr_apriori
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except Exception:
    weakref_proxy = lambda x: x



_gas_vmr_apriori.SHARED_PTR_DISOWN_swigconstant(_gas_vmr_apriori)
SHARED_PTR_DISOWN = _gas_vmr_apriori.SHARED_PTR_DISOWN

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import full_physics_swig.generic_object
import full_physics_swig.state_vector
class GasVmrApriori(full_physics_swig.generic_object.GenericObject):
    """

    Adapts the ReferenceVmrApriori class into a form that is easier to
    work with in the context of how this framework works.

    This class deals keys off of pressure levels like the rest of the
    framework. It also uses the increasing pressure levels convention.

    The VMR returned will be in the order of levels expected elsewhere in
    the framework.

    C++ includes: gas_vmr_apriori.h 
    """

    __swig_setmethods__ = {}
    for _s in [full_physics_swig.generic_object.GenericObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, GasVmrApriori, name, value)
    __swig_getmethods__ = {}
    for _s in [full_physics_swig.generic_object.GenericObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, GasVmrApriori, name)
    __repr__ = _swig_repr

    def __init__(self, Met_file, L1b_file, Alt, Hdf_static_input, Hdf_group, Gas_name, temp_avg_window):
        """

        FullPhysics::GasVmrApriori::GasVmrApriori(const boost::shared_ptr< Meteorology > &Met_file, const
        boost::shared_ptr< Level1b > &L1b_file, const boost::shared_ptr<
        Altitude > &Alt, const HdfFile &Hdf_static_input, const std::string
        &Hdf_group, const std::string &Gas_name, const int temp_avg_window=11)

        """
        this = _gas_vmr_apriori.new_GasVmrApriori(Met_file, L1b_file, Alt, Hdf_static_input, Hdf_group, Gas_name, temp_avg_window)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    @property
    def apriori_vmr(self):
        return self._v_apriori_vmr()


    def _v_apriori_vmr(self, *args):
        """

        const blitz::Array<double, 1> FullPhysics::GasVmrApriori::apriori_vmr(const Pressure &pressure) const

        """
        return _gas_vmr_apriori.GasVmrApriori__v_apriori_vmr(self, *args)


    def _v_reference(self):
        """

        const boost::shared_ptr<ReferenceVmrApriori> FullPhysics::GasVmrApriori::reference() const

        """
        return _gas_vmr_apriori.GasVmrApriori__v_reference(self)


    @property
    def reference(self):
        return self._v_reference()


    def _v_tropopause_altitude(self):
        """

        const DoubleWithUnit FullPhysics::GasVmrApriori::tropopause_altitude() const

        """
        return _gas_vmr_apriori.GasVmrApriori__v_tropopause_altitude(self)


    @property
    def tropopause_altitude(self):
        return self._v_tropopause_altitude()


    def _v_tropopause_pressure(self):
        """

        const double FullPhysics::GasVmrApriori::tropopause_pressure() const

        """
        return _gas_vmr_apriori.GasVmrApriori__v_tropopause_pressure(self)


    @property
    def tropopause_pressure(self):
        return self._v_tropopause_pressure()


    def __str__(self):
        return _gas_vmr_apriori.GasVmrApriori___str__(self)
    __swig_destroy__ = _gas_vmr_apriori.delete_GasVmrApriori
    __del__ = lambda self: None
GasVmrApriori_swigregister = _gas_vmr_apriori.GasVmrApriori_swigregister
GasVmrApriori_swigregister(GasVmrApriori)

# This file is compatible with both classic and new-style classes.


