# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_log_timing', [dirname(__file__)])
        except ImportError:
            import _log_timing
            return _log_timing
        if fp is not None:
            try:
                _mod = imp.load_module('_log_timing', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _log_timing = swig_import_helper()
    del swig_import_helper
else:
    import _log_timing
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except Exception:
    weakref_proxy = lambda x: x



_log_timing.SHARED_PTR_DISOWN_swigconstant(_log_timing)
SHARED_PTR_DISOWN = _log_timing.SHARED_PTR_DISOWN

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import full_physics_swig.connor_solver
import full_physics_swig.observer
import full_physics_swig.generic_object
class LogTiming(full_physics_swig.connor_solver.ObserverConnorSolver):
    """

    This is a helper class that logs basic timing information to the
    Logger.

    C++ includes: log_timing.h 
    """

    __swig_setmethods__ = {}
    for _s in [full_physics_swig.connor_solver.ObserverConnorSolver]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, LogTiming, name, value)
    __swig_getmethods__ = {}
    for _s in [full_physics_swig.connor_solver.ObserverConnorSolver]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, LogTiming, name)
    __repr__ = _swig_repr

    def __str__(self):
        return _log_timing.LogTiming___str__(self)

    def __init__(self):
        """

        FullPhysics::LogTiming::LogTiming()

        """
        this = _log_timing.new_LogTiming()
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def notify_update(self, Solver):
        """

        virtual void FullPhysics::LogTiming::notify_update(const ConnorSolver &Solver)

        """
        return _log_timing.LogTiming_notify_update(self, Solver)


    def write_to_log(self, *args):
        """

        virtual void FullPhysics::LogTiming::write_to_log(const std::string &Prefix="") const

        """
        return _log_timing.LogTiming_write_to_log(self, *args)

    __swig_destroy__ = _log_timing.delete_LogTiming
    __del__ = lambda self: None
LogTiming_swigregister = _log_timing.LogTiming_swigregister
LogTiming_swigregister(LogTiming)

# This file is compatible with both classic and new-style classes.


