# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_nlls_max_likelihood', [dirname(__file__)])
        except ImportError:
            import _nlls_max_likelihood
            return _nlls_max_likelihood
        if fp is not None:
            try:
                _mod = imp.load_module('_nlls_max_likelihood', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _nlls_max_likelihood = swig_import_helper()
    del swig_import_helper
else:
    import _nlls_max_likelihood
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except Exception:
    weakref_proxy = lambda x: x



_nlls_max_likelihood.SHARED_PTR_DISOWN_swigconstant(_nlls_max_likelihood)
SHARED_PTR_DISOWN = _nlls_max_likelihood.SHARED_PTR_DISOWN

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import full_physics_swig.nlls_problem
import full_physics_swig.cost_func_diff
import full_physics_swig.cost_func
import full_physics_swig.problem_state
import full_physics_swig.generic_object
import full_physics_swig.nlls_problem_state
import full_physics_swig.model_measure
import full_physics_swig.model_state
class NLLSMaxLikelihood(full_physics_swig.nlls_problem.NLLSProblem, full_physics_swig.nlls_problem_state.NLLSProblemState):
    """

    C++ includes: nlls_max_likelihood.h

    """

    __swig_setmethods__ = {}
    for _s in [full_physics_swig.nlls_problem.NLLSProblem, full_physics_swig.nlls_problem_state.NLLSProblemState]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, NLLSMaxLikelihood, name, value)
    __swig_getmethods__ = {}
    for _s in [full_physics_swig.nlls_problem.NLLSProblem, full_physics_swig.nlls_problem_state.NLLSProblemState]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, NLLSMaxLikelihood, name)
    __repr__ = _swig_repr

    def __init__(self, ml, together=False):
        """

        FullPhysics::NLLSMaxLikelihood::NLLSMaxLikelihood(const boost::shared_ptr< MaxLikelihood > &ml, bool together=false)
        Constructor. 
        """
        this = _nlls_max_likelihood.new_NLLSMaxLikelihood(ml, together)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _nlls_max_likelihood.delete_NLLSMaxLikelihood
    __del__ = lambda self: None

    def _v_residual(self):
        """

        virtual blitz::Array<double, 1> FullPhysics::NLLSMaxLikelihood::residual()
        Return the residual of the NLLS problem at the current set point.

        Residual 
        """
        return _nlls_max_likelihood.NLLSMaxLikelihood__v_residual(self)


    @property
    def residual(self):
        return self._v_residual()


    def _v_jacobian(self):
        """

        virtual blitz::Array<double, 2> FullPhysics::NLLSMaxLikelihood::jacobian()
        Return the Jacobian of the residual of the NLLS problem at the current
        set point.

        The Jacobian of the cost function. 
        """
        return _nlls_max_likelihood.NLLSMaxLikelihood__v_jacobian(self)


    @property
    def jacobian(self):
        return self._v_jacobian()


    def _v_residual_size(self):
        """

        virtual int FullPhysics::NLLSMaxLikelihood::residual_size() const
        Return the size of the residual that will be returned by residual() 
        """
        return _nlls_max_likelihood.NLLSMaxLikelihood__v_residual_size(self)


    @property
    def residual_size(self):
        return self._v_residual_size()


    def _v_expected_parameter_size(self):
        """

        virtual int FullPhysics::NLLSMaxLikelihood::expected_parameter_size() const
        Return the size of the parameter X. 
        """
        return _nlls_max_likelihood.NLLSMaxLikelihood__v_expected_parameter_size(self)


    @property
    def expected_parameter_size(self):
        return self._v_expected_parameter_size()


    def _v_parameters(self, *args):
        """

        virtual blitz::Array<double, 1> FullPhysics::NLLSMaxLikelihood::parameters() const
        Just returns the current values of parameters.

        This method is redefined here (see the root base class) because of a
        compiler bug; otherwise, there should be no need for its redefinition.

        Current parameter values 
        """
        return _nlls_max_likelihood.NLLSMaxLikelihood__v_parameters(self, *args)


    @property
    def parameters(self):
        return self._v_parameters()

    @parameters.setter
    def parameters(self, value):
      self._v_parameters(value)


    def _v_max_likelihood(self):
        """

        boost::shared_ptr<MaxLikelihood> FullPhysics::NLLSMaxLikelihood::max_likelihood()

        """
        return _nlls_max_likelihood.NLLSMaxLikelihood__v_max_likelihood(self)


    @property
    def max_likelihood(self):
        return self._v_max_likelihood()

NLLSMaxLikelihood_swigregister = _nlls_max_likelihood.NLLSMaxLikelihood_swigregister
NLLSMaxLikelihood_swigregister(NLLSMaxLikelihood)

# This file is compatible with both classic and new-style classes.


