# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pressure_sigma', [dirname(__file__)])
        except ImportError:
            import _pressure_sigma
            return _pressure_sigma
        if fp is not None:
            try:
                _mod = imp.load_module('_pressure_sigma', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pressure_sigma = swig_import_helper()
    del swig_import_helper
else:
    import _pressure_sigma
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except Exception:
    weakref_proxy = lambda x: x



_pressure_sigma.SHARED_PTR_DISOWN_swigconstant(_pressure_sigma)
SHARED_PTR_DISOWN = _pressure_sigma.SHARED_PTR_DISOWN

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import full_physics_swig.pressure_imp_base
import full_physics_swig.pressure
import full_physics_swig.state_vector
import full_physics_swig.generic_object
class PressureSigma(full_physics_swig.pressure_imp_base.PressureImpBase):
    __swig_setmethods__ = {}
    for _s in [full_physics_swig.pressure_imp_base.PressureImpBase]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PressureSigma, name, value)
    __swig_getmethods__ = {}
    for _s in [full_physics_swig.pressure_imp_base.PressureImpBase]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, PressureSigma, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pressure_sigma.new_PressureSigma(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def _v_surface_pressure_uncertainty(self):
        return _pressure_sigma.PressureSigma__v_surface_pressure_uncertainty(self)

    @property
    def surface_pressure_uncertainty(self):
        return self._v_surface_pressure_uncertainty()


    def set_surface_pressure(self, Surface_pressure):
        return _pressure_sigma.PressureSigma_set_surface_pressure(self, Surface_pressure)

    def set_levels_from_grid(self, Pressure_grid):
        return _pressure_sigma.PressureSigma_set_levels_from_grid(self, Pressure_grid)

    def clone(self):
        return _pressure_sigma.PressureSigma_clone(self)

    def state_vector_name_i(self, i):
        return _pressure_sigma.PressureSigma_state_vector_name_i(self, i)

    def _v_a(self):
        return _pressure_sigma.PressureSigma__v_a(self)

    @property
    def a(self):
        return self._v_a()


    def _v_b(self):
        return _pressure_sigma.PressureSigma__v_b(self)

    @property
    def b(self):
        return self._v_b()

    __swig_destroy__ = _pressure_sigma.delete_PressureSigma
    __del__ = lambda self: None
PressureSigma_swigregister = _pressure_sigma.PressureSigma_swigregister
PressureSigma_swigregister(PressureSigma)

# This file is compatible with both classic and new-style classes.


