# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_twostream_driver', [dirname(__file__)])
        except ImportError:
            import _twostream_driver
            return _twostream_driver
        if fp is not None:
            try:
                _mod = imp.load_module('_twostream_driver', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _twostream_driver = swig_import_helper()
    del swig_import_helper
else:
    import _twostream_driver
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except Exception:
    weakref_proxy = lambda x: x



_twostream_driver.SHARED_PTR_DISOWN_swigconstant(_twostream_driver)
SHARED_PTR_DISOWN = _twostream_driver.SHARED_PTR_DISOWN

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import full_physics_swig.generic_object
class TwostreamBrdfDriver(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TwostreamBrdfDriver, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TwostreamBrdfDriver, name)
    __repr__ = _swig_repr

    def __init__(self, surface_type):
        this = _twostream_driver.new_TwostreamBrdfDriver(surface_type)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _twostream_driver.delete_TwostreamBrdfDriver
    __del__ = lambda self: None

    def setup_geometry(self, sza, azm, zen):
        return _twostream_driver.TwostreamBrdfDriver_setup_geometry(self, sza, azm, zen)

    def _v_n_brdf_kernels(self):
        return _twostream_driver.TwostreamBrdfDriver__v_n_brdf_kernels(self)

    @property
    def n_brdf_kernels(self):
        return self._v_n_brdf_kernels()


    def _v_n_kernel_factor_wfs(self):
        return _twostream_driver.TwostreamBrdfDriver__v_n_kernel_factor_wfs(self)

    @property
    def n_kernel_factor_wfs(self):
        return self._v_n_kernel_factor_wfs()


    def _v_n_kernel_params_wfs(self):
        return _twostream_driver.TwostreamBrdfDriver__v_n_kernel_params_wfs(self)

    @property
    def n_kernel_params_wfs(self):
        return self._v_n_kernel_params_wfs()


    def _v_n_surface_wfs(self):
        return _twostream_driver.TwostreamBrdfDriver__v_n_surface_wfs(self)

    @property
    def n_surface_wfs(self):
        return self._v_n_surface_wfs()


    def _v_do_shadow_effect(self):
        return _twostream_driver.TwostreamBrdfDriver__v_do_shadow_effect(self)

    @property
    def do_shadow_effect(self):
        return self._v_do_shadow_effect()


    def _v_brdf_interface(self):
        return _twostream_driver.TwostreamBrdfDriver__v_brdf_interface(self)

    @property
    def brdf_interface(self):
        return self._v_brdf_interface()


    def do_kparams_derivs(self, kernel_index):
        return _twostream_driver.TwostreamBrdfDriver_do_kparams_derivs(self, kernel_index)
TwostreamBrdfDriver_swigregister = _twostream_driver.TwostreamBrdfDriver_swigregister
TwostreamBrdfDriver_swigregister(TwostreamBrdfDriver)

class TwostreamRtDriver(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TwostreamRtDriver, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TwostreamRtDriver, name)
    __repr__ = _swig_repr

    def __init__(self, nlayers, npars, surface_type, do_fullquadrature=True):
        this = _twostream_driver.new_TwostreamRtDriver(nlayers, npars, surface_type, do_fullquadrature)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def setup_height_grid(self, height_grid):
        return _twostream_driver.TwostreamRtDriver_setup_height_grid(self, height_grid)

    def setup_geometry(self, sza, azm, zen):
        return _twostream_driver.TwostreamRtDriver_setup_geometry(self, sza, azm, zen)

    def setup_optical_inputs(self, od, ssa, pf):
        return _twostream_driver.TwostreamRtDriver_setup_optical_inputs(self, od, ssa, pf)

    def clear_linear_inputs(self):
        return _twostream_driver.TwostreamRtDriver_clear_linear_inputs(self)

    def setup_linear_inputs(self, od, ssa, pf, do_surface_linearization):
        return _twostream_driver.TwostreamRtDriver_setup_linear_inputs(self, od, ssa, pf, do_surface_linearization)

    def calculate_rt(self):
        return _twostream_driver.TwostreamRtDriver_calculate_rt(self)

    def get_intensity(self):
        return _twostream_driver.TwostreamRtDriver_get_intensity(self)

    def copy_jacobians(self, jac_atm, jac_surf):
        return _twostream_driver.TwostreamRtDriver_copy_jacobians(self, jac_atm, jac_surf)

    def _v_twostream_brdf_driver(self):
        return _twostream_driver.TwostreamRtDriver__v_twostream_brdf_driver(self)

    @property
    def twostream_brdf_driver(self):
        return self._v_twostream_brdf_driver()


    def _v_brdf_interface(self):
        return _twostream_driver.TwostreamRtDriver__v_brdf_interface(self)

    @property
    def brdf_interface(self):
        return self._v_brdf_interface()


    def _v_twostream_interface(self):
        return _twostream_driver.TwostreamRtDriver__v_twostream_interface(self)

    @property
    def twostream_interface(self):
        return self._v_twostream_interface()


    def _v_do_full_quadrature(self):
        return _twostream_driver.TwostreamRtDriver__v_do_full_quadrature(self)

    @property
    def do_full_quadrature(self):
        return self._v_do_full_quadrature()


    def _v_pure_nadir(self):
        return _twostream_driver.TwostreamRtDriver__v_pure_nadir(self)

    @property
    def pure_nadir(self):
        return self._v_pure_nadir()

    __swig_destroy__ = _twostream_driver.delete_TwostreamRtDriver
    __del__ = lambda self: None
TwostreamRtDriver_swigregister = _twostream_driver.TwostreamRtDriver_swigregister
TwostreamRtDriver_swigregister(TwostreamRtDriver)

# This file is compatible with both classic and new-style classes.


